spring.application.name=Actividad_1_FullStack

# Spring tomará estos datos desde Render automáticamente
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración clave para RENDER (Toma el puerto de la nube)
server.port=${PORT:8080}